url: https://free-state-analytics.github.io/voxanalysis/
'package:': voxanalysis
title: VOX Analysis
description: An R package and shiny application for autism spectrum disorder diagnosis
template:
  bootstrap: 5
  bslib:
    base_font: {google: "Quicksand"}
    heading_font: {google: "Quicksand"}
  includes:
    in_header: |
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-65151TFP9L"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-65151TFP9L');
      </script>
authors:
  email: true
development:
  mode: auto


navbar:
  structure:
    left: [home, articles, reference]
    right: [search, github]
  components:
    home:
      text: "Home"
      href: https://free-state-analytics.github.io/voxanalysis/
    github:
      icon: fa fab fa-github fa-lg
      href: https://github.com/Free-State-Analytics/voxanalysis
    articles:
      text: "Articles"
      menu:
        - text: "Data Visualization & Charts"
          href: articles/datavizandcharts.html
        - text: "How to Generate Shiny Report"
          href: articles/generatingreports.html
        - text: "How to Generate Word Doc Report"
          href: articles/generatingword.html
        - text: "Data Definitions"
          href: articles/datadefinitions.html
        - text: "Data Structure Guidelines"
          href: articles/datamodel.html

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          install.packages('kableExtra')

      - name: Build and deploy pkgdown site
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages('pkgdown')
          pkgdown::build_site()
