#' Speaker Response Inputs (Example)
#'
#' This data set shows the structure expected for `df_input_response`, which is a common data set that's generated by the language assessment application.
#'
#' Each entry is a 1 or 0, which indicates whether a speaker responded to the referent.
#'
#' @format A data frame with 7 rows and 6 variables:
#' \describe{
#'   \item{date_of_evaluation}{The date of the evaluation.}
#'   \item{referent}{Name of the referent associated with the response.}
#'   \item{conversing}{Indicates whether the speaker provided a thematic response to an object (1 = Yes, 0 = No).}
#'   \item{labeling}{Indicates whether the speaker could label an object (1 = Yes, 0 = No).}
#'   \item{echoing}{Indicates whether the speaker could repeat an object name (1 = Yes, 0 = No).}
#'   \item{requesting}{Indicates whether the speaker could request an object name (1 = Yes, 0 = No).}
#' }
#'
#' @usage data(df_input_response_example)
#'
#' @seealso [df_input_response_previous_example]
"df_input_response_example"

#' Response Inputs Previous (Example)
#'
#' This sample data set is similar to `df_input_response_example`, but contains two previous set of evaluations. It is useful for producing examples of plots or analysis containing previous evaluation dates.
#'
#' Each entry is a 1 or 0, which indicates whether a speaker responded to the referent.
#'
#' @format A data frame with 7 rows and 6 variables:
#' \describe{
#'   \item{date_of_evaluation}{The date of the evaluation.}
#'   \item{referent}{Name of the referent associated with the response.}
#'   \item{conversing}{Indicates whether the speaker provided a thematic response to an object (1 = Yes, 0 = No).}
#'   \item{labeling}{Indicates whether the speaker could label an object (1 = Yes, 0 = No).}
#'   \item{echoing}{Indicates whether the speaker could repeat an object name (1 = Yes, 0 = No).}
#'   \item{requesting}{Indicates whether the speaker could request an object name (1 = Yes, 0 = No).}
#' }
#'
#' @usage data(df_input_response_previous_example)
#'
#' @seealso [df_input_response_example]
"df_input_response_previous_example"

#' Export Data (Example)
#'
#' This data set resembles the export of an evaluation. Any data that is re-imported to append new data will need to follow this structure.
#'
#' @format A data frame with 7 rows and 9 variables:
#' \describe{
#'   \item{first_name}{Speaker's first name.}
#'   \item{last_name}{Speaker's last name.}
#'   \item{date_of_birth}{The speaker's date of birth.}
#'   \item{language_spoken}{The language spoken during the evaluation.}
#'   \item{gender}{The speaker's gender.}
#'   \item{date_of_evaluation}{The date of the evaluation.}
#'   \item{referent}{Name of the referent associated with the response.}
#'   \item{conversing}{A binary indicator showing whether a speaker provided a thematic response to an object (1 = Yes, 0 = No).}
#'   \item{labeling}{A binary indicator showing whether the speaker could label an object (1 = Yes, 0 = No).}
#'   \item{echoing}{A binary indicator showing whether the speaker could repeat an object name (1 = Yes, 0 = No).}
#'   \item{requesting}{A binary indicator showing whether the speaker could request an object name (1 = Yes, 0 = No).}
#' }
#' @usage data(df_output_exportable_example)
"df_output_exportable_example"


#' Speaker Info (Example)
#'
#' This data set shows the expected structure for `df_input_speaker_info`, which is a common input required for function found in this package.
#'
#' @format A data frame with 1 rows and 4 variables:
#' \describe{
#'   \item{first_name}{Speaker's first name.}
#'   \item{last_name}{Speaker's last name.}
#'   \item{date_of_birth}{The speaker's date of birth.}
#'   \item{date_of_evaluation}{The date of the evaluation.}
#'   \item{language_spoken}{The language spoken during the evaluation.}
#'   \item{gender}{The speaker's gender.}
#'   }
#'
#' @usage data(df_input_speaker_info_example)
"df_input_speaker_info_example"


#' Summarized response
#'
#' This data set is a summation of the four response (conversing, labeling, echoing, and requesting). It is often used as an input for several plot functions.
#'
#' It can be produced using `summarize_response`. (See `?summarize_meausurments`.)
#'
#'
#' @format
#' \describe{
#'  \item{date_of_evaluation}
#'  \item{conversing}
#'  \item{labeling}
#'  \item{echoing}
#'  \item{requesting}
#' }
#' @usage data(df_summarized_response_example)
#' "df_summarized_response_example"
